title: Video Timestamps and Summaries for YouTube
description: Safari extension and macOS companion app for YouTube timestamps and summaries with Gemini.
url: https://hlbkomer.github.io
baseurl: /YouTube-Timestamps-and-Summaries
